failed to delete {'error': {'incident_id': '30B9C983', 'name': 'accounting_service.request.create_account', 'timestamp': '2013-10-24 20:45:09', 'context': '/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/accounting_service.nsvc1.skytap-dev.net-1.17613.accounting_service.request.create_account.42', 'msg': 'DataError(\'(DataError) (1406, "Data too long for column \\\'quota_pool_id\\\' at row 1")\',)', 'type': 'AccountingInternalError'}}: <Fault 1: '{"incident_id": "0E6D01BC", "name": "delete_account", "timestamp": "2013-10-24 20:45:10", "__severity": "error", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.delete_account.232", "func_name": "delete_account", "msg": "", "violations": [{"incident_id": "2EDF32EC", "name": "delete_account", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.delete_account.232", "msg": "delete_account parameter account_key type dict invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "53C4C0F6", "name": "delete_account", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.delete_account.232", "msg": "delete_account parameter account_key type dict invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}], "type": "InvalidParameters"}'>
test_concurrent_in_guest_poweroff_and_snapshot (__main__.ProvisioningTest) (Test that the system correctly handles snapshoting guests that are powered off concurrently with snapshot)... [ERROR]
Traceback (most recent call last):
  File "test_provisioning.py", line 134, in test_concurrent_in_guest_poweroff_and_snapshot
    with self.basic_configuration(account, charge_tag, vm_kwargs={'ram': 512}) as (configuration, network, vm, nic):
  File "/usr/lib/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/highland/hosting_platform/hosting_platform/system_tests/base.py", line 366, in basic_configuration
    with self.or_cm(account_depot, self.account_depot(account, 0, "scratch", 0)) as scratch_depot:
  File "/usr/lib/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/highland/hosting_platform/hosting_platform/system_tests/base.py", line 357, in or_cm
    with _else as value:
  File "/usr/lib/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/highland/hosting_platform/hosting_platform/system_tests/base.py", line 303, in account_depot
    depot = self.cm_api.create_depot(account, size, kind, capacity, config.HIGHLAND_ENV)
  File "/highland/hosting_platform/hosting_platform/common/monitoring/metric.py", line 211, in wrap
    return func(*args, **kwargs)
  File "/highland/hosting_platform/hosting_platform/rpc/CallNode.py", line 132, in __call__
    raise e
Fault: <Fault 1: '{"incident_id": "2A81F66F", "name": "create_depot", "timestamp": "2013-10-24 20:45:10", "__severity": "error", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "func_name": "create_depot", "msg": "", "violations": [{"incident_id": "368D5506", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter charge_tag type dict invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "5BC00BA1", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter account_key type int invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "3A368DDD", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter kind type int invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "630EF311", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter kind type int invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "586390A8", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter account_key type int invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}, {"incident_id": "07218685", "name": "create_depot", "context": "/ctx.15427.__main__.ProvisioningTest.test_concurrent_in_guest_poweroff_and_snapshot.1/configuration_manager-cm1-1.6381.create_depot.231", "msg": "create_depot parameter charge_tag type dict invalid, should be str", "timestamp": "2013-10-24 20:45:10", "type": "ParameterTypeError"}], "type": "InvalidParameters"}'>
RESULTS: Ran 1 test in 0.660s, FAILED (errors=1)
